environment:
  matrix:
    - nodejs_version: 0.8
    - nodejs_version: 0.10

platform:
  - x86

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - npm --version
  - cmd: SET PATH=c:\python27;%PATH%
  - npm install
  - npm test